#' summarizeMS
#' Main function to run MSformatR
#'
#' @param input Character vector specifying the location of the data to be summarized. By default all MA output in the current working directory will be used. Use of unix-style path seperators, /, is required. R will check the system and replace them with the correct path separator if running on Windows (see Details for additional information).
#' @param format Character value specifying the source of the raw data. Default is 'peaks11' (see Details).
#' @param qmd Character value specifying the path to supporting quarto documents. Default value is `./summary.qmd` (see Details).
#'
#' @details
#' When values are not supplied for function parameters, `summarizeMS` will look in the current working directory for a file called "config.yml" to supply these parameters. If no yaml config file is found, the default values specified here will be used instead.
#'
#' The path(s) for `input` can be specified using one of three formats:
#'
#' - An array of input directories (example yaml entry: `input: ["data/A", "data/B", "data/C"]`)
#' - A single path (example yaml entry: `input: "data/raw_results"`)
#' - A path to a directory containing multiple files to be summarized together. This should end in an `*`. (example yaml entry: `input: "data/*"`)
#'
#' Supported formats:
#'
#' - "peaks11" (default): html output from Peaks 11. Expected values for input are directory paths, each of which should contain multiple html files, csv files, and a directory of images.
#'
#' If no qmd file is provided, MSformatR will look for supporting quarto documents in the current working directory. If the required supporting files are not found, it will use documents installed with this package.
#'
#' Summary html pages will be generated by `summaryizeMS` as well as merged excel files when summarizing input from multiple samples.
#'
#' @export
#' @import rlang
#' @importFrom yaml read_yaml
#'
#' @importFrom magrittr %>%
#' @importFrom purrr map2
summarizeMS <- function(input = NULL, format = NULL, qmd = NULL)
{
  ##########
  # config #
  ##########

  config <- list(input  = input,
                 format = format,
                 qmd    = qmd)


  # look for config file and fill in any missing information
  if(file.exists('config.yml'))
  {
    tmp <- read_yaml('config.yml')

    for(i in names(config))
    {
      if(is.null(config[[i]]) & !is.null(tmp[[i]]))
        config[[i]] <- tmp[[i]]
    }
  }


  ##### Default configurations #####
  if(is.null(config$input))
    config$input <- file.path(getwd(), '*')

  if(is.null(config$format))
    config$format <- 'peaks11'

  if(is.null(config$qmd))
    config$qmd <- file.path(getwd(), 'summary.qmd')

  # look for required supporting files - if not found, use installed version
  if(!file.exists(config$qmd))
  {
    file.copy(system.file('quarto/summary.qmd', package = 'MSformatR'),
              config$qmd)
    cleanup_qmd <- TRUE
  }else{
    cleanup_qmd <- FALSE
  }


  ##### Check input files #####
  config$input <- check_file_inputs(config$input, config$format)


  ##### Process input #####
  processed_input <- map2(config$input, config$format, process_file_inputs)


  ##### Generate output #####
  map2(config$input, config$qmd, generate_html_output)


  ##### Clean up #####
  if(cleanup_qmd)
    file.remove(config$qmd)
}
